version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3402:3000"
        environment:
            NODE_ENV: production
