export const services = [
    {
        id: "fire-damage",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Fire.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Fire.svg",
        label: "Fire Damage Claims",
        href: "/fire-damage",
        icon: "solar:fire-bold",
    },
    {
        id: "water-damage",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Water.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Water.svg",
        label: "Water Damage Claims",
        href: "/water-damage",
        icon: "solar:water-drops-bold",
    },
    {
        id: "storm-damage",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Storm.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Storm.svg",
        label: "Storm Damage Claims",
        href: "/storm-damage",
        icon: "solar:thunder-bold",
    },
    {
        id: "mold-damage",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Mold.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Mold.svg",
        label: "Mold Damage Claims",
        href: "/mold-damage",
        icon: "solar:bacteria-bold",
    },
    {
        id: "commercial",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Commercial.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Commercial.svg",
        label: "Commercial Claims",
        href: "/commercial",
        icon: "solar:buildings-bold",
    },
    {
        id: "general-cleaning",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Cleaning_Services.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Cleaning_Services.svg",
        label: "General Cleaning",
        href: "/general-cleaning",
        icon: "solar:washing-machine-bold",
    },
    {
        id: "specialty-cleaning",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_COVID_Cleaning.svg",
        altText: "SERV1429_L1sp_Icons_Dark_COVID_Cleaning.svg",
        label: "Specialty cleaning",
        href: "/specialty-cleaning",
        icon: "solar:broom-bold",
    },
    {
        id: "construction",
        imgSrc: "/assets/images/icons/SERV1429_L1sp_Icons_Dark_Construction.svg",
        altText: "SERV1429_L1sp_Icons_Dark_Construction.svg",
        label: "Construction",
        href: "/construction",
        icon: "solar:hammer-bold",
    },
];

export default services;
